figury: main.o punkt.o figura.o kolo.o pierscien.o trojkat.o
	g++ -o program main.o punkt.o figura.o kolo.o pierscien.o trojkat.o

main.o: main.cpp
	g++ -c main.cpp

punkt.o: punkt.cpp
	g++ -c punkt.cpp

figura.o: figura.cpp
	g++ -c figura.cpp

kolo.o: kolo.cpp
	g++ -c kolo.cpp

pierscien.o: pierscien.cpp
	g++ -c pierscien.cpp

trojkat.o: trojkat.cpp
	g++ -c trojkat.cpp

